spring.datasource.url=jdbc:postgresql://localhost:5432/banco_xyz
spring.datasource.username=postgres
spring.datasource.password=hola123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false