spring.application.name=banco-xyz-batch

spring.datasource.url=jdbc:postgresql://localhost:5432/banco_xyz
spring.datasource.username=postgres
spring.datasource.password=hola123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always

spring.batch.jdbc.initialize-schema=always

spring.batch.job.enabled=false

# ---------- Parametros de negocio ----------
banco.tasa.ahorro=0.005
banco.tasa.prestamo=0.015

banco.edad.minima=18
banco.edad.maxima=100